name: Example workflow using Snyk

on:
  push:
    branches:
      - main  # or specify the branch you want to trigger on

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Install Snyk CLI
      run: npm install -g snyk

    - name: Run Snyk to check for vulnerabilities and generate SARIF report
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      run: snyk test --sarif-file-output=snyk.sarif

    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: snyk.sarif
